# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: gitui
    init: |
      cargo build
      make install
    command: gitui
    
vscode:
  extensions:
    - rust-lang.rust
